### ISSUE TITLE
no __version__ argument

### ISSUE THREAD

**Issue by londumas** [veeresht/CommPy#104]
There does not seem to be a __version__ argument for the package.

```
import commpy

commpy.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-68df451740b3> in <module>
----> 1 commpy.__version__

AttributeError: module 'commpy' has no attribute '__version__'
```

```
python -m pip show scikit-commpy
Name: scikit-commpy
Version: 0.7.0
```

**Comment by BastienTr** [comment]
Your right, there is no such argument. I'm not familiar with the convention. Is the version argument a PEP-recommended thing?

**Comment by BastienTr** [comment]
Hi @londumas,

I just checked and the [PEP396](https://www.python.org/dev/peps/pep-0396/#id22) seems to promote the following solution rather than the uses of `__version__`. 

``` python
from importlib.metadata import version
version('scikit-commpy')
```
