### ISSUE TITLE
NumPy log2 bug in QAMModem class 

### ISSUE THREAD

**Issue by veeresht** [veeresht/CommPy#11]
There's a sort-of bug in the QAMModem class (at least on some python implementations). From your example above:
self.num_bits_symbol returns 5 instead of 6 (for QAMModem(64))
log2(64) = 5.99999...
then int(log2(64)) = 5
Note: log(64)/log(2) = 6.0.
I'm using python-2.7.5.amd64 on Win10.
- reported by Keith Douglas (http://veeresht.info/blog/cfo.html)

**Comment by kirlf** [comment]
Just tried with Python 3.8, this bug has already been fixed:

```python
import numpy as np
int(np.log2(64))

>>> 6
```

**Comment by BastienTr** [comment]
Thanks!
