### ISSUE TITLE
Unable to Install in Powershell

### ISSUE THREAD

**Issue by djxvillain** [veeresht/CommPy#114]
Unable to install in PS.  I am able to install numpy, scipy, and matplotlib without an issue.

> PS C:\Users\dylan> pip install scikit-commpy
> Collecting scikit-commpy
>   Using cached scikit-commpy-0.7.0.tar.gz (52 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [8 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\dylan\AppData\Local\Temp\pip-install-go1gdf4x\scikit-commpy_b26dfb1cc7994ec4858ea1db4aee768f\setup.py", line 9, in <module>
>           LONG_DESCRIPTION = open('README.md').read()
>         File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
>           return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>       UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5282: character maps to <undefined>
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

**Comment by BastienTr** [comment]
Both #114 and this issue refers to a bad caracter in the README.md file. I will try to fix this ASAP.

**Comment by BastienTr** [comment]
PR #117 should fix the problem. I'll push on pip ASAP.

**Comment by BastienTr** [comment]
Pushed on pip. The package should be installable on all platform.

Feel free to reopen if you encounter the problem again.
