### ISSUE TITLE
Can not install using pip

### ISSUE THREAD

**Issue by liuzhen0107** [veeresht/CommPy#115]
D:\Program Files\Anaconad\Scripts>pip install scikit-commpy
Collecting scikit-commpy
  Using cached scikit-commpy-0.7.0.tar.gz (52 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Program Files\Anaconad\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\10122692\\AppData\\Local\\Temp\\pip-install-gqoop340\\scikit-commpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\10122692\\AppData\\Local\\Temp\\pip-install-gqoop340\\scikit-commpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\10122692\AppData\Local\Temp\pip-pip-egg-info-fwv8ghow'
         cwd: C:\Users\10122692\AppData\Local\Temp\pip-install-gqoop340\scikit-commpy\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\10122692\AppData\Local\Temp\pip-install-gqoop340\scikit-commpy\setup.py", line 9, in <module>
        LONG_DESCRIPTION = open('README.md').read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 5282: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by BastienTr** [comment]
Closed as dupliacte of #114
