### ISSUE TITLE
Question about get_ldpc_code_params

### ISSUE THREAD

**Issue by Jubo-Xu** [veeresht/CommPy#116]
Sorry, when I use get_ldpc_code_params(), there's always an error of ValueError: invalid literal for int() with base 10: ..., even if I use the 96.33.964.txt in the test example. May I ask how could I fix this error?

**Comment by BastienTr** [comment]
Could you provide a code snippet that I can test on my computer?

**Comment by Jubo-Xu** [comment]
Sorry, this function doesn't work for me even for the simplest code:
_**import torch
import numpy as np
import commpy.channelcoding.ldpc as ldpc
import scipy.sparse as sp
import scipy.sparse.linalg as splg

ldpc.get_ldpc_code_params('Headers/gallager_96_33_964.txt')**_

gallager_96_33_964.txt is same as the 96.33.964.txt provided, I just put it under the directory of my project. If I simply use ldpc.get_ldpc_code_params, the error is 'IndexError: index 95 is out of bounds for axis 0 with size 95', but if I define a LDPC class for it:
**_import torch
import numpy as np
import commpy.channelcoding.ldpc as ldpc


def sparse_dense_mul(s, d):
    # TODO make this general for any dims
    i = s._indices()
    v = s._values()
    # get values from relevant entries of dense matrix
    dv = d[i[0, :], i[1, :], i[2, :]]
    #dv = d[i[0, :], i[1, :]]
    return torch.sparse_coo_tensor(i, v * dv, d.size())

def get_ldpc_code_params(ldpc_design_filename, compute_matrix=False):

    with open(ldpc_design_filename) as ldpc_design_file:

        [n_vnodes, n_cnodes] = [int(x) for x in ldpc_design_file.readline().split(' ')]
        [max_vnode_deg, max_cnode_deg] = [int(x) for x in ldpc_design_file.readline().split(' ')]
        vnode_deg_list = np.array([int(x) for x in ldpc_design_file.readline().split(' ')[:-1]], np.int32)
        cnode_deg_list = np.array([int(x) for x in ldpc_design_file.readline().split(' ')[:-1]], np.int32)

        cnode_adj_list = -np.ones([n_cnodes, max_cnode_deg], int)
        vnode_adj_list = -np.ones([n_vnodes, max_vnode_deg], int)

        for vnode_idx in range(n_vnodes):
            vnode_adj_list[vnode_idx, 0:vnode_deg_list[vnode_idx]] = \
                np.array([int(x)-1 for x in ldpc_design_file.readline().split('\t')])

        for cnode_idx in range(n_cnodes):
            cnode_adj_list[cnode_idx, 0:cnode_deg_list[cnode_idx]] = \
                np.array([int(x)-1 for x in ldpc_design_file.readline().split('\t')])

    cnode_vnode_map = -np.ones([n_cnodes, max_cnode_deg], int)
    vnode_cnode_map = -np.ones([n_vnodes, max_vnode_deg], int)

    for cnode in range(n_cnodes):
        for i, vnode in enumerate(cnode_adj_list[cnode, 0:cnode_deg_list[cnode]]):
            cnode_vnode_map[cnode, i] = np.where(vnode_adj_list[vnode, :] == cnode)[0]

    for vnode in range(n_vnodes):
        for i, cnode in enumerate(vnode_adj_list[vnode, 0:vnode_deg_list[vnode]]):
            vnode_cnode_map[vnode, i] = np.where(cnode_adj_list[cnode, :] == vnode)[0]

    cnode_adj_list_1d = cnode_adj_list.flatten().astype(np.int32)
    vnode_adj_list_1d = vnode_adj_list.flatten().astype(np.int32)
    cnode_vnode_map_1d = cnode_vnode_map.flatten().astype(np.int32)
    vnode_cnode_map_1d = vnode_cnode_map.flatten().astype(np.int32)

    ldpc_code_params = {}

    ldpc_code_params['n_vnodes'] = n_vnodes
    ldpc_code_params['n_cnodes'] = n_cnodes
    ldpc_code_params['max_cnode_deg'] = max_cnode_deg
    ldpc_code_params['max_vnode_deg'] = max_vnode_deg
    ldpc_code_params['cnode_adj_list'] = cnode_adj_list_1d
    ldpc_code_params['cnode_vnode_map'] = cnode_vnode_map_1d
    ldpc_code_params['vnode_adj_list'] = vnode_adj_list_1d
    ldpc_code_params['vnode_cnode_map'] = vnode_cnode_map_1d
    ldpc_code_params['cnode_deg_list'] = cnode_deg_list
    ldpc_code_params['vnode_deg_list'] = vnode_deg_list

    if compute_matrix:
        ldpc.build_matrix(ldpc_code_params)

    return ldpc_code_params
    
    
# BP-SP Decoding algorithm

def ldpc_bp_decode(llr_vec, ldpc_code_params, H, decoder_algorithm, n_iters):
    _llr_max = 500
    #N = 1
    #print(f"llr size: {llr_vec.shape}")
    B, N, L = llr_vec.size()
    out_llrs = llr_vec.clone()
    out_word = llr_vec < 0 #torch.signbit(llr_vec)
    n_c = ldpc_code_params['n_cnodes']
    n_v = ldpc_code_params['n_vnodes']
    #N = 1
    recover_indices = torch.arange(0, n_c*N, n_c).to(llr_vec.device)

    llr_vec = llr_vec.clamp(-_llr_max, _llr_max)  # clip LLRs
    llr_vec = llr_vec.repeat_interleave(n_c, dim=1)

    # Initialization
    dec_word = llr_vec < 0 #torch.signbit(llr_vec)
    msg_llrs = llr_vec.clone()

    parity_check_matrix = H.to(torch.float).unsqueeze(0).repeat_interleave(B, dim=0)
    parity_check_matrix = parity_check_matrix.repeat(1, N, 1).to_sparse()

    message_matrix = sparse_dense_mul(parity_check_matrix, llr_vec)

    for iter_cnt in range(n_iters):
        iterations = iter_cnt + 1
        term_check = sparse_dense_mul(parity_check_matrix, dec_word)
        term_check = torch.sparse.sum(term_check, dim=2)
        term_check = term_check.to_dense().view(B, N, n_c) % 2
        term_check = torch.chunk(term_check, chunks=B, dim=0)

        curr_llr = torch.index_select(msg_llrs, 1, recover_indices)
        curr_word = torch.index_select(dec_word, 1, recover_indices)
        nan_mask = torch.isnan(curr_llr)
        out_llrs[~nan_mask] = curr_llr[~nan_mask]
        out_word[~nan_mask] = curr_word[~nan_mask]

        if decoder_algorithm == 'SPA':
            message_matrix *= .5
            message_matrix = torch.sparse_coo_tensor(message_matrix._indices(),
                                                     torch.tanh(message_matrix._values()),
                                                     message_matrix.size())

            log2_msg_matrix = torch.sparse_coo_tensor(message_matrix._indices(),
                                                      torch.log2(message_matrix._values()),
                                                      message_matrix.size())

            msg_products_real = torch.sparse_coo_tensor(log2_msg_matrix._indices(),
                                                        log2_msg_matrix._values(),
                                                        log2_msg_matrix.size())
            msg_products_real = torch.sparse.sum(msg_products_real, dim=2)
            
            msg_products = msg_products_real
            
            #msg_products_imag = torch.sparse_coo_tensor(log2_msg_matrix._indices(), log2_msg_matrix._values().imag, log2_msg_matrix.size())
            
            #msg_products_imag = torch.sparse.sum(msg_products_imag, dim=2)
            
            '''msg_products = torch.sparse_coo_tensor(msg_products_real._indices(),
                                                   torch.view_as_complex(
                                                       torch.stack((msg_products_real._values(),
                                                                    msg_products_imag._values()),
                                                                   dim=1)),
                                                   msg_products_real.size())'''
            msg_products = torch.sparse_coo_tensor(msg_products._indices(),
                                                   (2 ** msg_products._values()),
                                                   msg_products.size())

            message_matrix = torch.sparse_coo_tensor(message_matrix._indices(),
                                                     (1 / message_matrix._values()),
                                                     message_matrix.size())

            message_matrix = sparse_dense_mul(message_matrix,
                                              msg_products.to_dense().unsqueeze(2).repeat_interleave(n_v, dim=2))

            message_matrix = torch.sparse_coo_tensor(message_matrix._indices(),
                                                     message_matrix._values().clamp(-1, 1),
                                                     message_matrix.size())
            message_matrix = torch.sparse_coo_tensor(message_matrix._indices(),
                                                     torch.atan(message_matrix._values()),      # or arctan
                                                     message_matrix.size())

            message_matrix *= 2
            message_matrix = torch.sparse_coo_tensor(message_matrix._indices(),
                                                     message_matrix._values().clamp(-_llr_max, _llr_max),
                                                     message_matrix.size())
        else:
            raise NotImplementedError('Only SPA is implemented for now')

        msg_sum = message_matrix.to_dense()
        msg_sum = msg_sum.view(B, N, -1, n_v)
        msg_sum = msg_sum.sum(2)
        msg_sum = msg_sum.repeat_interleave(n_c, dim=1)

        message_matrix *= -1
        message_matrix = torch.sparse_coo_tensor(message_matrix._indices(),
                                                 (message_matrix._values()
                                                  + sparse_dense_mul(parity_check_matrix, (msg_sum + llr_vec))._values()),
                                                 message_matrix.size())

        msg_llrs = (msg_sum + llr_vec).to(torch.float)
        dec_word = msg_llrs < 0 #torch.signbit(msg_llrs)

    return out_word.to(torch.float), out_llrs.to(torch.float32), iterations



class LDPC:
    def __init__(self, header_fn, decode_iters, device):
        self.ldpc_design = self.load_code_from_alist(header_fn)
        self.G = torch.from_numpy(self.ldpc_design['generator_matrix'].A).to(device).transpose(1, 0)
        self.H = torch.from_numpy(self.ldpc_design['parity_check_matrix'].A).to(device)
        self.k = self.G.shape[0]
        self.n = self.H.shape[1]
        self.decode_algorithm = 'SPA'  # TODO MSA not yet impl
        self.decode_iters = decode_iters
        self.device = device

    def load_code_from_alist(self, header_fn):
        params = get_ldpc_code_params(header_fn, compute_matrix=True)
        params['decode_algorithm'] = 'SPA'
        return params
    
    def zero_pad(self, x, modulo):
        B, _, L = x.size()
        if torch.numel(x[0]) % modulo != 0:
            n_pad = (modulo*L) - (torch.numel(x[0]) % (modulo*L))
            zero_pad = torch.zeros(B, n_pad, device=x.device).view(B, -1, L)
            padded_message = torch.cat((x, zero_pad), dim=1)
        else:
            padded_message = x
        return padded_message
    
   

    def encode(self, message_bits):
        N = 1
        B, N, L = message_bits.size()
        padded_message = self.zero_pad(message_bits, self.k)
        padded_message = padded_message.view(B, -1, self.k)
        parity = torch.matmul(padded_message, self.G) % 2
        codeword = torch.cat((padded_message, parity), dim=-1)
        return codeword

    def decode(self, symbol_llr):
        #print(f"llr size: {symbol_llr.shape}")
        # NOTE process batch by batch due to memory use
        batch_llr = torch.chunk(symbol_llr, chunks=1, dim=0)
        out_llr = []
        for b_llr in batch_llr:
            block_llr = torch.chunk(b_llr, chunks=2, dim=1)
            d_llr = []
            for llr_i in block_llr:
                decoded_bits, llr, _ = ldpc_bp_decode(llr_i, self.ldpc_design, self.H,
                                           self.decode_algorithm, self.decode_iters)
                d_llr.append(llr)

            d_llr = torch.cat(d_llr, dim=1)
            out_llr.append(d_llr)

        llr = torch.cat(out_llr, dim=0)
        return decoded_bits, llr_** 

and I use 'code = LDPC(args.header_fn, args.decoding_iterations, args.device)', where the args.header_fn is the file of BCH_7_4_1_strip.alist, which is 
7 3
3 4
1 1 2 2 3 2 1 
4 4 4 
1 0 0
2 0 0
1 3 0
1 2 0
1 2 3
2 3 0
3 0 0
1 3 4 5 
2 4 5 6 
3 5 6 7 
then the error will be 'ValueError: invalid literal for int() with base 10: '1 0 0\n''. In both cases, the error is from np.array([int(x)-1 for x in ldpc_design_file.readline().split('\t')]) of get_ldpc_code_params().

**Comment by Jubo-Xu** [comment]
Sorry, this function doesn't work for me even for the simplest code:
import torch
import numpy as np
import commpy.channelcoding.ldpc as ldpc
import scipy.sparse as sp
import scipy.sparse.linalg as splg

ldpc.get_ldpc_code_params('Headers/gallager_96_33_964.txt')**_

gallager_96_33_964.txt is same as the 96.33.964.txt provided, I just put it under the directory of my project. If I simply use ldpc.get_ldpc_code_params, the error is 'IndexError: index 95 is out of bounds for axis 0 with size 95', but if I define a LDPC class for it:
class LDPC:
def init(self, header_fn, decode_iters, device):
self.ldpc_design = self.load_code_from_alist(header_fn)
self.G = torch.from_numpy(self.ldpc_design['generator_matrix'].A).to(device).transpose(1, 0)
self.H = torch.from_numpy(self.ldpc_design['parity_check_matrix'].A).to(device)
self.k = self.G.shape[0]
self.n = self.H.shape[1]
self.decode_algorithm = 'SPA' # TODO MSA not yet impl
self.decode_iters = decode_iters
self.device = device

def load_code_from_alist(self, header_fn):
    params = get_ldpc_code_params(header_fn, compute_matrix=True)
    params['decode_algorithm'] = 'SPA'
    return params

def zero_pad(self, x, modulo):
    B, _, L = x.size()
    if torch.numel(x[0]) % modulo != 0:
        n_pad = (modulo*L) - (torch.numel(x[0]) % (modulo*L))
        zero_pad = torch.zeros(B, n_pad, device=x.device).view(B, -1, L)
        padded_message = torch.cat((x, zero_pad), dim=1)
    else:
        padded_message = x
    return padded_message



def encode(self, message_bits):
    N = 1
    B, N, L = message_bits.size()
    padded_message = self.zero_pad(message_bits, self.k)
    padded_message = padded_message.view(B, -1, self.k)
    parity = torch.matmul(padded_message, self.G) % 2
    codeword = torch.cat((padded_message, parity), dim=-1)
    return codeword

def decode(self, symbol_llr):
    #print(f"llr size: {symbol_llr.shape}")
    # NOTE process batch by batch due to memory use
    batch_llr = torch.chunk(symbol_llr, chunks=1, dim=0)
    out_llr = []
    for b_llr in batch_llr:
        block_llr = torch.chunk(b_llr, chunks=2, dim=1)
        d_llr = []
        for llr_i in block_llr:
            decoded_bits, llr, _ = ldpc_bp_decode(llr_i, self.ldpc_design, self.H,
                                       self.decode_algorithm, self.decode_iters)
            d_llr.append(llr)

        d_llr = torch.cat(d_llr, dim=1)
        out_llr.append(d_llr)

    llr = torch.cat(out_llr, dim=0)
    return decoded_bits, llr
and I use 'code = LDPC(args.header_fn, args.decoding_iterations, args.device)', where the args.header_fn is the file of BCH_7_4_1_strip.alist, which is
7 3
3 4
1 1 2 2 3 2 1
4 4 4
1 0 0
2 0 0
1 3 0
1 2 0
1 2 3
2 3 0
3 0 0
1 3 4 5
2 4 5 6
3 5 6 7
then the error will be 'ValueError: invalid literal for int() with base 10: '1 0 0\n''. In both cases, the error is from np.array([int(x)-1 for x in ldpc_design_file.readline().split('\t')]) of get_ldpc_code_params().

**Comment by Jubo-Xu** [comment]
Sorry, this function doesn't work for me even for the simplest code:
import torch
import numpy as np
import commpy.channelcoding.ldpc as ldpc
import scipy.sparse as sp
import scipy.sparse.linalg as splg

ldpc.get_ldpc_code_params('Headers/gallager_96_33_964.txt')**_

gallager_96_33_964.txt is same as the 96.33.964.txt provided, I just put it under the directory of my project. If I simply use ldpc.get_ldpc_code_params, the error is 'IndexError: index 95 is out of bounds for axis 0 with size 95', but if I define a LDPC class for it:
class LDPC:
     def init(self, header_fn, decode_iters, device):
            self.ldpc_design = self.load_code_from_alist(header_fn)
            self.G = torch.from_numpy(self.ldpc_design['generator_matrix'].A).to(device).transpose(1, 0)
            self.H = torch.from_numpy(self.ldpc_design['parity_check_matrix'].A).to(device)
            self.k = self.G.shape[0]
            self.n = self.H.shape[1]
            self.decode_algorithm = 'SPA' # TODO MSA not yet impl
            self.decode_iters = decode_iters
            self.device = device

     def load_code_from_alist(self, header_fn):
            params = get_ldpc_code_params(header_fn, compute_matrix=True)
            params['decode_algorithm'] = 'SPA'
            return params

     def zero_pad(self, x, modulo):
            B, _, L = x.size()
            if torch.numel(x[0]) % modulo != 0:
                   n_pad = (moduloL) - (torch.numel(x[0]) % (moduloL))
                   zero_pad = torch.zeros(B, n_pad, device=x.device).view(B, -1, L)
                   padded_message = torch.cat((x, zero_pad), dim=1)
            else:
                   padded_message = x
            return padded_message

     def encode(self, message_bits):
            N = 1
            B, N, L = message_bits.size()
            padded_message = self.zero_pad(message_bits, self.k)
            padded_message = padded_message.view(B, -1, self.k)
            parity = torch.matmul(padded_message, self.G) % 2
            codeword = torch.cat((padded_message, parity), dim=-1)
            return codeword

     def decode(self, symbol_llr):
            batch_llr = torch.chunk(symbol_llr, chunks=1, dim=0)
            out_llr = []
            for b_llr in batch_llr:
                   block_llr = torch.chunk(b_llr, chunks=2, dim=1)
                   d_llr = []
                   for llr_i in block_llr:
                              decoded_bits, llr, _ = ldpc_bp_decode(llr_i, self.ldpc_design, self.H,
                              self.decode_algorithm, self.decode_iters)
                              d_llr.append(llr)
                   d_llr = torch.cat(d_llr, dim=1)
                   out_llr.append(d_llr)
             llr = torch.cat(out_llr, dim=0)
             return decoded_bits, llr
and I use 'code = LDPC(args.header_fn, args.decoding_iterations, args.device)', where the args.header_fn is the file of BCH_7_4_1_strip.alist, which is
7 3
3 4
1 1 2 2 3 2 1
4 4 4
1 0 0
2 0 0
1 3 0
1 2 0
1 2 3
2 3 0
3 0 0
1 3 4 5
2 4 5 6
3 5 6 7
then the error will be 'ValueError: invalid literal for int() with base 10: '1 0 0\n''. In both cases, the error is from np.array([int(x)-1 for x in ldpc_design_file.readline().split('\t')]) of get_ldpc_code_params().

**Comment by BastienTr** [comment]
You're encountering two different issues.

For the first one, being:

``` python
import numpy as np
import commpy.channelcoding.ldpc as ldpc
import scipy.sparse as sp
import scipy.sparse.linalg as splg

ldpc.get_ldpc_code_params('Headers/gallager_96_33_964.txt')
```

everything work as expected. I used both my main interpreter with a lot of packages and a fresh install with `pip install scikit-commpy`. 

Here are the packages installed on the fresh install

```
cycler==0.11.0
fonttools==4.37.2
kiwisolver==1.4.4
matplotlib==3.5.3
mpmath==1.2.1
numpy==1.21.6
packaging==21.3
Pillow==9.2.0
pyparsing==3.0.9
python-dateutil==2.8.2
scikit-commpy==0.7.0
scipy==1.7.3
six==1.16.0
sympy==1.10.1
typing_extensions==4.3.0
```

---

Your second file `BCH_7_4_1_strip.alist` contains several formatting errors:

 * is badly structured. As explained in the docstring, 

https://github.com/veeresht/CommPy/blob/9496b1fe7b51a9dc872543941b1bcd293b3608b0/commpy/channelcoding/ldpc.py#L60-L61

the vnodes et cnodes have to be seperated by '\t'.

 * The first 4 lines serves as a header containing (seperated by ' ') :

https://github.com/veeresht/CommPy/blob/9496b1fe7b51a9dc872543941b1bcd293b3608b0/commpy/channelcoding/ldpc.py#L56-L59

Your file lacks one header line.

**Comment by BastienTr** [comment]
Closed since the error is not reproductible in its current description. Feel free to re-open with new information.
