### ISSUE TITLE
modulaiton.py PSKModem constellation not using numpy array

### ISSUE THREAD

**Issue by elysoto** [veeresht/CommPy#28]
self.constellation = map(self._constellation_symbol,
                                 self.symbol_mapping)

in the constructor, should be

self.constellation = array(map(self._constellation_symbol,
                                 self.symbol_mapping))

similar to what QAMModem is doing.

Otherwise, this type error occurs. 
TypeError: list indices must be integers, not list

**Comment by BastienTr** [comment]
Hi Elysoto,

Can you check that this issue still occures when cloning the GitHub repo rather than using the pip version ? In modulation.py lines 116/117 :
```self.constellation = list(map(self.constellation, self.symbol_mapping))```.
