### ISSUE TITLE
help to improve library

### ISSUE THREAD

**Issue by hadadiashkan** [veeresht/CommPy#34]
Hello,
In case of a desire to adding new modulation and so on, I will be glad to help you.
Ashkan.

**Comment by BastienTr** [comment]
Hello,
Any help is obviously welcome. Currently, we don't have any precise plan on the module or features to add. If you have any interesting ideas, feel free to fork this repo, implent it and make a PR.

You can also help by solving some issues or adding unit tests where the are missing.
I close this issue as it's not the best place to discuss about it but don't hesitate to contact @veeresht and I by email (veeresht@gmail.com & bastien.trotobas@gmail.com). We could find together the way to help that suits you better.

Thanks beforehand for your help.
Bastien
