### ISSUE TITLE
Wrong direct push & Python 2 in Travis

### ISSUE THREAD

**Issue by BastienTr** [veeresht/CommPy#51]
Veeresh,

I mistakenly made a direct push rather than a PR (bad configuration of my new damn IDE...). The new version is no longer compatible with python 2.

Could you please check that the push suits you (if not you can do a revert), I prefer not to revert myself in order not to add more mess in the tree. Indeed, as you will see the addition is quite basic.

You should also remove Python 2 from Travis to avoid compatibility errors that no longer make sense with the end of Python 2.

**Comment by veeresht** [comment]
Removed python 2 dependency in travis.yml.

**Comment by BastienTr** [comment]
Thanks :+1:
