### ISSUE TITLE
v0.5 release

### ISSUE THREAD

**Issue by BastienTr** [veeresht/CommPy#53]
Hi @veeresht,

I drafted a new release as the new content seems enough to justify it. Does it look good to you?
If so, I'll make the release and try to update pip. If I remember well, you haded me as a contributor on pip.

> This version abandons Python 2 compatibility and all tests are now validated on Python 3.
> The Conda version is no longer updated but pip should be updated accordingly as soon as possible.
> 
> * The convolutional code module now supports puncturing, all code ratios and provides a method for tracing FSM.
> * LDPC encoder, design saving utilities, WiMAX designs and BP decoder enhancements.
> * A tool to estimate the BER performance of a link model using a Monte Carlo estimator.
> * K-best MIMO detector.
> * Updates and corrections in the doc.
> * Several bug fixes.

**Comment by veeresht** [comment]
@BastienTr  That looks :+1: Please release it on PyPi (where pip installs from. Thank you! :smile:

**Comment by BastienTr** [comment]
Ok I'll have a try ASAP.

I was wondering if we should go for v0.5 or v1.0 as, according to [semantic versionning](https://semver.org/) v1 is reached when the API and the backward compatibility are settled.

**Comment by veeresht** [comment]
Not too sure or have any preferences. Maybe stick with 0.5 for now and try to make it a 1.0 when we have more test coverage and potentially more users and features ? Calling it 1.0 raises the expectations on the software a bit I guess :smiley:

**Comment by BastienTr** [comment]
That sounds good to me :)

**Comment by BastienTr** [comment]
Here we go :+1: 
https://pypi.org/project/scikit-commpy/0.5.0/
I direct pushed the changed setup.py (see 1c031f9bf0b0e8cf1518dcbeff117cf49f358df9).
