### ISSUE TITLE
Plotting modulated signals?

### ISSUE THREAD

**Issue by jeichenhofer** [veeresht/CommPy#56]
Hello everyone,

I'm working on an encoding/modulating setup much like the example in https://github.com/veeresht/CommPy/blob/master/commpy/examples/conv_encode_decode.py. I think I have a good start on understanding the process, but my background in signals processing is a bit lacking. I'm hoping someone here can help me with the next steps.

For context, my goal is to form a relatively reliable communication scheme over a noisy (and potentially transcoded/compressed) audio channel. I've been referencing this library and another called [amodem](https://github.com/romanz/amodem), but it seems like this library is missing the component for actually generating audio and the other library does not incorporate any error correcting codes and does not survive my tests through the audio channel.

I'm at a point where, with [the code here](https://github.com/jeichenhofer/voiceover/blob/master/CodecModem.py), I can take binary data and generate complex QAM symbols. My understanding is that each QAM symbol represents the amplitude and and phase of one baud's signal (at the carrier's frequency). I'd like to graph this signal as a raw waveform, but I'm unsure how to do that. This is as far as I got, but it seems cumbersome to be calculating the amplitude and phase explicitly for each symbol:

```python
f_w = 2*np.pi*carrier_hz
t_series = np.arange(0, 1/baud, 1/sample_hz)
wave_samples = np.abs(curr_qam) * np.cos(f_w * np.angle(curr_qam) * t_series)

plt.plot(t_series, wave_samples)
plt.show()
```

If I do this for every QAM symbol and concatenate the results, I _think_ that would be exactly the signal transmitted over some analog medium (after passed through some DAC), but I wonder if there is a better/simpler or more elegant way of doing this with the CommPy library.

**Comment by veeresht** [comment]
@jeichenhofer I think what you're doing is pretty much how you visualize the amplitude and phase of the baseband signal as you mentioned. Another way is to create a 2D plot of the modulated QAM symbols by plotting the real and imaginary parts on the x, y axes as pairs i.e., each QAM symbol represents a point on the 2D XY plane. This should look somewhat like this (for a 64-QAM constellation). You should see small clouds where the points are depending on how much noise you add. Hope this helps!
 
![image](https://user-images.githubusercontent.com/760356/78208513-6c883a80-7459-11ea-921d-fbd8da9a976d.png)

**Comment by jeichenhofer** [comment]
Thank you for the insight. I think I've got a good understanding of the complex plane representation of the QAM constellations. What I'm really trying to get is a way to generate the actual waveform which I can transmit across the audio channel.

For example, this method below (I think) does what I want, but I'm not sure if it's the most mathematically appropriate way of working with the complex QAM symbols. Furthermore, I will have to do the "inverse" where I sample an audio signal and extract the QAM symbols. I think if I understand how to work with the complex QAM symbols more intuitively, that will help with the whole process.

```python
import numpy as np


def gen_waveform(qam_symbols: np.ndarray, sym_baud: int = 4, sample_hz: int = 8e3, carrier_hz: int = 1e3):
    """
    Create a sampled audio waveform based on the provided QAM symbols.

    The Skype encoding algorithm potentially uses a sample rate of 16kHz, so we will default to a sample rate that is
    half of that in order to avoid major problems in the transcoding and compression pipeline. Similarly, our carrier
    frequency will be one-eigth of our own sample rate, allowing for no chance of missing the nyquist rate for sampling
    arbitrary modulations to the waveform.

    :param qam_symbols: 1d array of complex floats representing qam symbols to generate the audio
    :param sym_baud: frequency of symbols per second (NOT actual baud bits per second)
    :param sample_hz: sampling frequency to use for the generated waveform
    :param carrier_hz: carrier tone (cosine wave) frequency to modulate

    :return: sampled audio as 1d array of floats representing raw values at each sample
    """
    f_w = 2*np.pi*carrier_hz
    t_series = np.arange(0, 1/sym_baud, 1/sample_hz)

    wave_samples = []

    for curr_qam_s in qam_symbols:
        curr_samples = np.abs(curr_qam_s) * np.cos(f_w * np.angle(curr_qam_s) * t_series)
        wave_samples = np.append(wave_samples, curr_samples)

    from datetime import datetime as dt
    timestamp = dt.utcnow().isoformat()

    import wavio
    normalized = (wave_samples - np.min(wave_samples)) / np.ptp(wave_samples)
    centered = 2*normalized - 1
    scaled = np.int16(centered * 32767)  # max value of int16 = 32767
    wavio.write('data/{}.wav'.format(timestamp), scaled, sample_hz, sampwidth=2)
```

**Comment by BastienTr** [comment]
Hi @jeichenhofer,
Do you still need help on this or can I close this issue? If you need more help, could you please do an update? I'll have some free time this week and next week so that I could have a closer look.

**Comment by jeichenhofer** [comment]
Thanks for the response. I actually got something working! You can close this issue, and some time this summer I'll open a pull request to get my code in the examples directory for the modulation component of this project.

**Comment by BastienTr** [comment]
I look forward to see your PR.
Have a nice weekend.
