### ISSUE TITLE
Gray Coding

### ISSUE THREAD

**Issue by safarisadegh** [veeresht/CommPy#60]
I checked out 16-QAM modulation and saw that the constellation is not using gray coding. My question is that will be available in next versions?

**Comment by BastienTr** [comment]
Indeed the constellation are at the moment the most basic one. Gray coding could be included in the next version or not. We don't have any precise plan. Added features depends mostly on the PR that we receive. Feel free to have a look to add this, I'll be happy to assist you on this.
