### ISSUE TITLE
Specification of decimal equivalent of polynomial (g_matrix entry) for trellis

### ISSUE THREAD

**Issue by aklsh** [veeresht/CommPy#62]
Hey,

I want to know how to specify the g_matrix entries as decimals. The problem is, I have the generator polynomials, but don't know how to convert them to decimal numbers.

Say one of the polynomials is 1+D^2+D^3, for a memory=3 encoder. Does this correspond to a binary number of 1011 (LSB first format) or 1101 (MSB first format)? In both the examples given in the documentation, the binary number is symmetric.

**Comment by BastienTr** [comment]
Hey @aklsh,

Thanks for your interest on this project! The format is MSB first (for instance 1+D <-> 3 <-> 011). In your example, you should use `13` or `0o15`.

Please, let me know if you spot an error with this format but I'm quite sure that this is the right way. I'll add you're example to the example file and make some change to the doc to explicit this feature. Could you keep this issue open until then.

**Comment by aklsh** [comment]
Okay. I just figured out what to use and was about to post the same.

_Just a suggestion_: In the Matlab equivalent `convenc`, we specify the polynomial as 1011 i.e., decimal 11 or `0o13` for 1+D^2+D^3. So, it would be nice if format used here can match that, so that people can have one standard format across platforms. I think it will only take an additional line of code to reverse the numpy array, got from dec2binarray()

**Comment by BastienTr** [comment]
Yes. It would be interesting for sure. I'm just wondering how to detect if 1101 means the polymonial with a binary format or the integer 1101. Any suggestion?

**Comment by BastienTr** [comment]
Another way of preserving the retro-compatibility while allowing to use the Matlab LSB format is to add a new argument that specified the format. It would be a string `'MSB' ` or `'LSB' `. This string would have a default value to `'MSB'` to keep the current format. The doc should then highlights that `'LSB' ` is the Matlab format.

Is this a goor option?

**Comment by aklsh** [comment]
What I had in mind was preserving the specification of polynomials in form of decimals, but adding another argument (say, `matlab=true`) so that the binary array returned from `dec2binarray` can be reversed using a simple if statement.

But what you said also sounds good.

**Comment by BastienTr** [comment]
Currently, it is possible to specify the polynomial in hexadecimal/octal format.

I'll add the new argument as it seems to fit what we are looking to do here.

**Comment by BastienTr** [comment]
I just had the argument `polynomial_format` that accept `'MSB'`, `'LSB'` and `'Matlab'` to Treillis.
