### ISSUE TITLE
Coverage is not computed since commit 2b102b7

### ISSUE THREAD

**Issue by BastienTr** [veeresht/CommPy#79]
I noticed that the coverage reports are no more updated since commit 2b102b7. PR #50 shows the last coverage output. The section **Recent builds** on https://coveralls.io/github/veeresht/CommPy confirms that there are no more builds.

@veeresht any clues or fixes?

**Comment by BastienTr** [comment]
According to the [last Travis build](https://travis-ci.org/github/veeresht/CommPy/builds/719296014) lines 796 and further, the `coveralls` command fails with `ImportError: cannot import name 'Reporter'`.

**Comment by veeresht** [comment]
![image](https://user-images.githubusercontent.com/760356/90667223-578f2680-e203-11ea-89d7-01cc35595aec.png)

:smile: :clap: :clap: :+1:

**Comment by BastienTr** [comment]
Great! :clap: :smiley:
