### ISSUE TITLE
Travis CI build failing for Python 3.3

### ISSUE THREAD

**Issue by veeresht** [veeresht/CommPy#8]
- File "/home/travis/build/veeresht/CommPy/commpy/__init__.py", line 17, in <module>
    from filters import *
ImportError: No module named 'filters'

- commpy/channelcoding/algcode   NotPython: Couldn't parse '/home/travis/build/veeresht/CommPy/commpy/channelcoding/algcode.py' as Python source: 'invalid syntax' at line 35

- commpy/channelcoding/gfields   NotPython: Couldn't parse '/home/travis/build/veeresht/CommPy/commpy/channelcoding/gfields.py' as Python source: 'invalid syntax' at line 63

- commpy/channelcoding/tests/test_convcode   NotPython: Couldn't parse '/home/travis/build/veeresht/CommPy/commpy/channelcoding/tests/test_convcode.py' as Python source: 'invalid token' at line 17

**Comment by quantumdude836** [comment]
Prefixing `commpy.` to all the import statements fixed the `ImportError` for me. Tested with python 3.5.1 on Ubuntu 16.04.
